import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SoladoyeolaOS
 */
public class Decryption extends javax.swing.JFrame {

    /**
     * Creates new form Decryption
     */
    JFileChooser fchooser = new JFileChooser();
    BufferedReader br;
    FileReader fr;
    String line;
    String page = "";
    StringBuffer sb;
    String DecryptedWord = "";
    int textLenght = 0;
    char[] filleText;
    char[] newWord ;
    char[] upperCode = new char[]{
    'A','B','C','D','E',
    'F','G','H','I','J',
    'K','L','M','N','O',
    'P','Q','R','S','T',
    'U','V','W','X','Y',
    'Z'};
    char[] lowerCode = new char[]{
    'a','b','c','d','e',
    'f','g','h','i','j',
    'k','l','m','n','o',
    'p','q','r','s','t',
    'u','v','w','x','y',
    'z'};
    char[] numCode = new char[]{
        '0','1','2','3','4',
        '5','6','7','8','9'
    };
    public Decryption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPath = new javax.swing.JLabel();
        btnChoose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        btnDecrypt = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChoose.setText("CHOOSE FILE");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane1.setViewportView(txtDisplay);

        btnDecrypt.setText("DECRYPT FILE");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE FILE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChoose)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(btnDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPath, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblPath, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnChoose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        if(fchooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            try {
                File myfile = fchooser.getSelectedFile();
                lblPath.setText(myfile.toString());
                fr = new FileReader(myfile);
                br = new BufferedReader(fr);
                sb = new StringBuffer();
                try {
                    while ((line = br.readLine()) != null) {
                        page = line + "\n"+page;
                        textLenght = page.length();
                        filleText = new char[textLenght];
                        newWord = new char[textLenght];
                    }
                    //System.out.print(page);
                    for(int i = 0; i < textLenght; i++){
                        filleText[i] = page.charAt(i);
                        System.out.print(filleText[i]);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Encryption.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Encryption.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        // TODO add your handling code here:
        if(textLenght != 0){
            for(int i = 0; i < filleText.length; i++){
                //System.out.println(filleText[i]);
                //System.out.print(newWord[i]);
                if(filleText[i] == 'A'){
                newWord[i] = lowerCode[13];
            }else if(filleText[i] == 'B'){
                newWord[i] = lowerCode[14];
            }else if(filleText[i] == 'C'){
                newWord[i] = lowerCode[15];
            }else if(filleText[i] == 'D'){
                newWord[i] = lowerCode[16];
            }else if(filleText[i] == 'E'){
                newWord[i] = lowerCode[17];
            }else if(filleText[i] == 'F'){
                newWord[i] = lowerCode[18];
            }else if(filleText[i] == 'G'){
                newWord[i] = lowerCode[19];
            }else if(filleText[i] == 'H'){
                newWord[i] = lowerCode[20];
            }else if(filleText[i] == 'I'){
                newWord[i] = lowerCode[21];
            }else if(filleText[i] == 'J'){
                newWord[i] = lowerCode[22];
            }else if(filleText[i] == 'K'){
                newWord[i] = lowerCode[23];
           }else if(filleText[i] == 'L'){
                newWord[i] = lowerCode[24];
           }else if(filleText[i] == 'M'){
                newWord[i] = lowerCode[25];
            }else if(filleText[i] == 'N'){
                newWord[i] = lowerCode[0];
            }else if(filleText[i] == 'O'){
                newWord[i] = lowerCode[1];
            }else if(filleText[i] == 'P'){
                newWord[i] = lowerCode[2];
            }else if(filleText[i] == 'Q'){
                newWord[i] = lowerCode[3];
            }else if(filleText[i] == 'R'){
                newWord[i] = lowerCode[4];
            }else if(filleText[i] == 'S'){
                newWord[i] = lowerCode[5];
            }else if(filleText[i] == 'T'){
                newWord[i] = lowerCode[6];
            }else if(filleText[i] == 'U'){
                newWord[i] = lowerCode[7];
            }else if(filleText[i] == 'V'){
                newWord[i] = lowerCode[8];
           }else if(filleText[i] == 'W'){
                newWord[i] = lowerCode[9];
           }else if(filleText[i] == 'X'){
                newWord[i] = lowerCode[10];
            }else if(filleText[i] == 'Y'){
                newWord[i] = lowerCode[11];
           }else if(filleText[i] == 'Z'){
                newWord[i] = lowerCode[12];
                //lower case chech
           }else if(filleText[i] == 'a'){
                newWord[i] = upperCode[13];
            }else if(filleText[i] == 'b'){
                newWord[i] = upperCode[14];
            }else if(filleText[i] == 'c'){
                newWord[i] = upperCode[15];
            }else if(filleText[i] == 'd'){
                newWord[i] = upperCode[16];
            }else if(filleText[i] == 'e'){
                newWord[i] = upperCode[17];
            }else if(filleText[i] == 'f'){
                newWord[i] = upperCode[18];
            }else if(filleText[i] == 'g'){
                newWord[i] = upperCode[19];
            }else if(filleText[i] == 'h'){
                newWord[i] = upperCode[20];
            }else if(filleText[i] == 'i'){
                newWord[i] = upperCode[21];
            }else if(filleText[i] == 'j'){
                newWord[i] = upperCode[22];
            }else if(filleText[i] == 'k'){
                newWord[i] = upperCode[23];
           }else if(filleText[i] == 'l'){
                newWord[i] = upperCode[24];
           }else if(filleText[i] == 'm'){
                newWord[i] = upperCode[25];
            }else if(filleText[i] == 'n'){
                newWord[i] = upperCode[0];
            }else if(filleText[i] == 'o'){
                newWord[i] = upperCode[1];
            }else if(filleText[i] == 'p'){
                newWord[i] = upperCode[2];
            }else if(filleText[i] == 'q'){
                newWord[i] = upperCode[3];
            }else if(filleText[i] == 'r'){
                newWord[i] = upperCode[4];
            }else if(filleText[i] == 's'){
                newWord[i] = upperCode[5];
            }else if(filleText[i] == 't'){
                newWord[i] = upperCode[6];
            }else if(filleText[i] == 'u'){
                newWord[i] = upperCode[7];
            }else if(filleText[i] == 'v'){
                newWord[i] = upperCode[8];
           }else if(filleText[i] == 'w'){
                newWord[i] = upperCode[9];
           }else if(filleText[i] == 'x'){
                newWord[i] = upperCode[10];
            }else if(filleText[i] == 'y'){
                newWord[i] = upperCode[11];
           }else if(filleText[i] == 'z'){
                newWord[i] = upperCode[12];
           }else if(filleText[i] == '0'){
                newWord[i] = numCode[6];
           }else if(filleText[i] == '1'){
                newWord[i] = numCode[3];
           }else if(filleText[i] == '2'){
                newWord[i] = numCode[0];
           }else if(filleText[i] == '3'){
                newWord[i] = numCode[9];
           }else if(filleText[i] == '4'){
                newWord[i] = numCode[8];
           }else if(filleText[i] == '5'){
                newWord[i] = numCode[7];
           }else if(filleText[i] == '6'){
                newWord[i] = numCode[5];
           }else if(filleText[i] == '7'){
                newWord[i] = numCode[1];
           }else if(filleText[i] == '8'){
                newWord[i] = numCode[4];
           }else if(filleText[i] == '9'){
                newWord[i] = numCode[2];
           }else if(filleText[i] == ' '){
                newWord[i] = ' ';
           }else if(filleText[i] == '\n'){
                newWord[i] = '\n';
           }
            DecryptedWord += String.valueOf(newWord[i]);
            txtDisplay.setText(DecryptedWord);
            }
        }
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decryption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPath;
    private javax.swing.JTextArea txtDisplay;
    // End of variables declaration//GEN-END:variables
}
